'''
Author: wbs2788
Date: 2023-12-13 09:15:54
LastEditTime: 2023-12-13 09:38:56
LastEditors: wbs2788
Description: 
FilePath: \Arxiv-Daily\stopword.py

'''
# AI相关的停用词列表
AI_STOPWORDS = {
    'algorithm', 'algorithms', 'system', 'systems', 'method', 'methods',
    'approach', 'approaches', 'model', 'models', 'technique', 'techniques',
    'task', 'tasks', 'problem', 'problems', 'solution', 'solutions',
    'application', 'applications', 'research', 'study', 'studies',
    'paper', 'papers', 'article', 'articles', 'field', 'fields',
    'data', 'result', 'results', 'performance', 'analysis', 'analyses',
    'network', 'networks', 'learning', 'machine', 'intelligence',
    'artificial', 'neural', 'deep', 'reinforcement', 'learning',
    'supervised', 'unsupervised', 'semi', 'structured', 'unstructured',
    'data', 'dataset', 'datasets', 'feature', 'features', 'classifier',
    'classifiers', 'classification', 'regression', 'prediction',
    'predictive', 'algorithmic', 'computation', 'computational',
    'statistical', 'statistic', 'statistics', 'robotics', 'robot',
    'robots', 'automation', 'automated', 'processing', 'processor',
    'cognitive', 'cognition', 'computer', 'computing', 'technology',
    'technologies', 'digital', 'information', 'informatic', 'informatics',
    'systematic', 'framework', 'frameworks', 'architecture', 'architectures',
    'implementation', 'implementations', 'development', 'developments',
    'design', 'designs', 'modeling', 'modelling', 'simulation', 'simulations',
    'evaluation', 'evaluations', 'validation', 'validations', 'experiment',
    'experiments', 'experimental', 'empirical', 'study', 'studies',
    'analysis', 'analyses', 'analytic', 'analytics', 'theoretical', 
    'theory', 'theories', 'concept', 'concepts', 'context', 'contexts',
    'mechanism', 'mechanisms', 'dynamic', 'dynamics', 'static', 'statics',
    'adaptive', 'adaptation', 'optimization', 'optimize', 'optimizing',
    'efficient', 'efficiency', 'effective', 'effectiveness', 'accuracy',
    'accurate', 'precision', 'precise', 'robust', 'robustness', 'scalable',
    'scalability', 'secure', 'security', 'safe', 'safety', 'intelligent',
    'intelligence', 'capability', 'capabilities', 'capacity', 'functional',
    'functionality', 'quality', 'quantitative', 'quantify', 'quantifying',
    'qualitative', 'qualify', 'qualifying', 'demonstrate', 'demonstrates',
    'demonstrating', 'demonstration', 'demonstrations', 'indicate', 
    'indicates', 'indicating', 'indication', 'indications', 'illustrate',
    'illustrates', 'illustrating', 'illustration', 'illustrations', 
    'show', 'shows', 'showing', 'example', 'examples', 'instance', 'instances',
    'form', 'forms', 'type', 'types', 'kind', 'kinds', 'category', 'categories',
    'group', 'groups', 'part', 'parts', 'version', 'versions', 'aspect', 'aspects',
    'level', 'levels', 'stage', 'stages', 'phase', 'phases', 'process', 'processes',
    'procedure', 'procedures', 'strategy', 'strategies', 'tactic', 'tactics',
    'plan', 'plans', 'planning', 'project', 'projects', 'program', 'programs',
    'initiative', 'initiatives', 'goal', 'goals', 'objective', 'objectives',
    'target', 'targets', 'aim', 'aims', 'purpose', 'purposes', 'intent', 'intents',
    'intention', 'intentions', 'scope', 'limit', 'limits', 'limitation', 'limitations',
    'constraint', 'constraints', 'challenge', 'challenges', 'issue', 'issues',
    'factor', 'factors', 'element', 'elements', 'component', 'components', 'unit', 'units',
    'structure', 'structures', 'sequence', 'sequences', 'series', 'array', 'arrays',
    'range', 'ranges', 'variety', 'varieties', 'diversity', 'diverse', 'multiple',
    'various', 'several', 'numerous', 'different', 'varied', 'assortment', 'assortments',
    'mixture', 'mixtures', 'combination', 'combinations', 'array', 'arrays', 'range', 
    'ranges', 'spectrum', 'spectra', 'selection', 'selections', 'choice', 'choices',
    'option', 'options', 'alternative', 'alternatives', 'variability', 'variable',
    'variables', 'variation', 'variations', 'variety', 'varieties', 'diversity',
    'diverse', 'difference', 'differences', 'distinct', 'distinctive', 'unique',
    'novel', 'new', 'modern', 'current', 'contemporary', 'recent', 'latest', 'up-to-date',
    'state-of-the-art', 'cutting-edge', 'advanced', 'advancement', 'advance', 'advances',
    'progress', 'progressive', 'innovation', 'innovative', 'innovate', 'innovating',
    'creation', 'create', 'creating', 'creator', 'creators', 'invention', 'invent',
    'inventing', 'inventor', 'inventors', 'develop', 'developing', 'developer', 
    'developers', 'development', 'developments', 'design', 'designing', 'designer', 
    'designers', 'build', 'building', 'builder', 'builders', 'construct', 'constructing',
    'constructor', 'constructors', 'construction', 'constructions', 'fabricate', 
    'fabricating', 'fabrication', 'fabrications', 'manufacture', 'manufacturing', 
    'manufacturer', 'manufacturers', 'production', 'produce', 'producing', 'producer',
    'producers', 'generate', 'generating', 'generator', 'generators', 'creation', 
    'creating', 'creator', 'creators', 'formulate', 'formulating', 'formulation', 
    'formulations', 'compose', 'composing', 'composition', 'compositions', 'assemble', 
    'assembling', 'assembly', 'assemblies', 'synthesize', 'synthesizing', 'synthesis', 
    'syntheses', 'transform', 'transforming', 'transformation', 'transformations', 
    'alter', 'altering', 'alteration', 'alterations', 'modify', 'modifying', 'modification',
    'modifications', 'change', 'changing', 'conversion', 'conversions', 'convert', 'converting',
    'adapt', 'adapting', 'adaptation', 'adaptations', 'adjust', 'adjusting', 'adjustment',
    'adjustments', 'revise', 'revising', 'revision', 'revisions', 'edit', 'editing', 'editor',
    'editors', 'rewrite', 'rewriting', 'update', 'updating', 'upgrade', 'upgrading', 'enhance',
    'enhancing', 'enhancement', 'enhancements', 'improve', 'improving', 'improvement', 
    'improvements', 'amend', 'amending', 'amendment', 'amendments', 'refine', 'refining', 
    'refinement', 'refinements', 'perfect', 'perfecting', 'perfection', 'optimize', 'optimizing',
    'optimization', 'optimizations', 'streamline', 'streamlining', 'simplify', 'simplifying',
    'simplification', 'simplifications', 'clarify', 'clarifying', 'clarification', 'clarifications',
    'elucidate', 'elucidating', 'elucidation', 'elucidations', 'explicate', 'explicating', 
    'explication', 'explications', 'illustrate', 'illustrating', 'illustration', 'illustrations',
    'demonstrate', 'demonstrating', 'demonstration', 'demonstrations', 'exemplify', 'exemplifying',
    'exemplification', 'exemplifications', 'represent', 'representing', 'representation', 'representations',
    'depict', 'depicting', 'depiction', 'depictions', 'image', 'based', 'using', 'images', 'AI', 'via', 'text',
    'training', 'propose', 'introduce', 'existing', 'http', 'github', 'without'
}